disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
  - control_statement
  - type_name
  - line_length
#  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  - cyclomatic_complexity
 #- file length
  # Find all the available rules by running:
  # swiftlint rules
whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
