# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrainningIOS112017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for TrainningIOS112017

  target 'TrainningIOS112017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrainningIOS112017UITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'SwiftLint'
end
